// Agent Assist portable demo -- rendering logic.
// All data comes from data.js (DATA global, generated by generate_data.py).
// Chart.js instances are cached per canvas id so tab switches / filter
// changes destroy-and-recreate instead of leaking canvases.

const CHARTS = {};
const COLOR = {
  aa: '#0071CE', nonAa: '#F59E0B', overall: '#001E60',
  good: '#1E8E3E', bad: '#C5221F', muted: '#9CA3AF',
};
const ENDPOINT_COLORS = {
  genai: '#6366f1', northstar: '#3b82f6', smart: '#10b981',
  non_smart: '#8b5cf6', default: '#f59e0b', cca2: '#ef4444',
};
const ENDPOINT_LABELS = {
  genai: 'Legacy GenAI', northstar: 'Northstar', smart: 'Smart Transition',
  non_smart: 'Non-Smart', default: 'Default Handoff', cca2: 'Redirect to CCA2',
};

// ── Formatting helpers ────────────────────────────────────────────────────────
const fmtAHT = v => v == null ? '\u2014' : `${v.toFixed(1)}s`;
const fmtPct = v => v == null ? '\u2014' : `${v.toFixed(1)}%`;
const fmtNPS = v => v == null ? '\u2014' : (v >= 0 ? `+${v.toFixed(1)}` : v.toFixed(1));
const fmtNum = v => v == null ? '\u2014' : Math.round(v).toLocaleString();

function deltaSpan(aaVal, nonAaVal, lowerIsBetter) {
  if (aaVal == null || nonAaVal == null) return '';
  const diff = aaVal - nonAaVal;
  const better = lowerIsBetter ? diff < 0 : diff > 0;
  const cls = better ? 'good' : 'bad';
  const sign = diff > 0 ? '+' : '';
  return `<span class="kpi-delta ${cls}">${sign}${diff.toFixed(1)} vs Non-AA</span>`;
}

function mkChart(canvasId, config) {
  const el = document.getElementById(canvasId);
  if (!el) return;
  if (CHARTS[canvasId]) CHARTS[canvasId].destroy();
  CHARTS[canvasId] = new Chart(el.getContext('2d'), config);
}

// Resample a daily [dates, values] pair into Weekly (7-day avg) or Monthly
// (30-day avg) buckets. 'Daily' is a passthrough. Nulls are ignored in the
// average (so survey-lag gap days don't drag a whole week to zero).
function resample(dates, series, grain) {
  if (grain === 'Daily' || !dates || !dates.length) return { dates, series };
  const bucketSize = grain === 'Weekly' ? 7 : 30;
  const outDates = [];
  const outSeries = {};
  Object.keys(series).forEach(k => outSeries[k] = []);
  for (let i = 0; i < dates.length; i += bucketSize) {
    outDates.push(dates[i]);
    Object.keys(series).forEach(k => {
      const chunk = series[k].slice(i, i + bucketSize).filter(v => v != null);
      outSeries[k].push(chunk.length ? chunk.reduce((a, b) => a + b, 0) / chunk.length : null);
    });
  }
  return { dates: outDates, series: outSeries };
}

function lineDataset(label, data, color, extra = {}) {
  return { label, data, borderColor: color, backgroundColor: color, tension: 0.25, pointRadius: 2, borderWidth: 2, spanGaps: true, ...extra };
}

// ── Strategic Insights + Metric Readout (shared across every tab) ────────────
// Every tab gets one of these right under its KPI cards: a few sentences of
// specific, numbers-driven narrative ("what does this mean"), plus a compact
// AA/Non-AA readout strip so the raw figures backing the narrative are
// visible at a glance without re-reading the KPI cards above.
function insightsCard(title, bullets, readoutHtml = '') {
  const bulletHtml = bullets.map(b => `<li>${b}</li>`).join('');
  return `
    <div class="insights-card">
      <h3>${title}</h3>
      <ul class="insights-list">${bulletHtml}</ul>
      ${readoutHtml}
    </div>`;
}

function metricReadout(rows) {
  // rows: [{ label, aa, naa, fmt }]
  const cells = rows.map(r => `
    <div class="readout-cell">
      <div class="readout-label">${r.label}</div>
      <div class="readout-values">
        <span class="readout-aa">${r.fmt(r.aa)}</span>
        <span class="readout-sep">vs</span>
        <span class="readout-naa">${r.fmt(r.naa)}</span>
      </div>
    </div>`).join('');
  return `
    <div class="readout-strip">
      <div class="readout-legend">
        <span class="legend-swatch" style="background:${COLOR.aa}"></span>AA
        <span class="legend-swatch" style="background:${COLOR.nonAa};margin-left:14px"></span>Non-AA
      </div>
      <div class="readout-grid">${cells}</div>
    </div>`;
}

const baseLineOpts = {
  responsive: true, maintainAspectRatio: false,
  interaction: { mode: 'index', intersect: false },
  plugins: { legend: { position: 'bottom', labels: { boxWidth: 10, font: { size: 11 } } } },
  scales: { x: { ticks: { maxTicksLimit: 8, font: { size: 10 } } }, y: { ticks: { font: { size: 10 } } } },
};

// ── Current filter state ───────────────────────────────────────────────────
const state = { channel: 'all', group: 'all', grain: 'Daily' };

// ── Filter-driven data scaling ──────────────────────────────────────
// The dataset in data.js represents the full "All channels / All agent
// groups" population. Selecting a Channel or Agent Group filter re-scales
// every displayed number through a fixed mix profile -- the same idea the
// Channel Matrix widget already used, just applied across every tab so the
// whole filter bar actually does something everywhere, not just in one
// widget. Profiles are directional assumptions for demo purposes only
// (e.g. voice contacts run longer AHT than chat), not measured splits.
const CHANNEL_PROFILE = {
  all:   { count: 1.00, aht: 1.00, pct: 1.00, score: 1.00 },
  voice: { count: 0.62, aht: 1.12, pct: 0.97, score: 0.95 },
  chat:  { count: 0.38, aht: 0.79, pct: 1.04, score: 1.05 },
};
const GROUP_PROFILE = {
  all:              { count: 1.00, aht: 1.00, pct: 1.00, score: 1.00 },
  alpha_group:      { count: 0.79, aht: 0.98, pct: 1.01, score: 1.02 },
  ab_test_500pairs: { count: 0.21, aht: 1.05, pct: 0.96, score: 0.94 },
};

function scaleFactor(family, { channelOnly = false } = {}) {
  const c = CHANNEL_PROFILE[state.channel][family];
  const g = channelOnly ? 1 : GROUP_PROFILE[state.group][family];
  return c * g;
}

/** Scale one numeric value by the current channel/group filter. `family` is
 * one of 'aht' (unbounded seconds), 'pct' (0-100), 'score' (0-100 NPS/
 * sentiment), or 'count' (contacts/agents, rounded to an integer). */
function scaled(value, family, opts) {
  if (value == null) return null;
  const v = value * scaleFactor(family, opts);
  if (family === 'pct' || family === 'score') return Math.max(0, Math.min(100, v));
  if (family === 'count') return Math.round(v);
  return v;
}

function scaledArr(arr, family, opts) {
  return (arr || []).map(v => scaled(v, family, opts));
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 1 -- Metric Definitions (static content, formulas only, no live data)
// ══════════════════════════════════════════════════════════════════════════
function renderMetricDefs() {
  const endpoints = [
    { name: 'Legacy GenAI', color: '#6366f1', desc: 'The entry point (Cyborg service). Responsible for the initial execution and Welcome Message.' },
    { name: 'Northstar', color: '#3b82f6', desc: 'The ADK-based advanced GenAI workflow orchestration.' },
    { name: 'Smart Transition', color: '#10b981', desc: 'Intent-based CCA2 experience within AA where a specific Guided Workflow is pre-selected for the agent.' },
    { name: 'Default Handoff', color: '#f59e0b', desc: 'The entry-point widget where agents manually search/select a workflow within AA.' },
    { name: 'Non-Smart', color: '#8b5cf6', desc: 'A post-handoff state within CCA2 in AA used for workflow switching or handling secondary issues, especially during or after a Smart Handoff.' },
    { name: 'Redirect to CCA2', color: '#ef4444', desc: '"Fail-Safe" mechanism. A button-based fallback for systematic failures to traditional CCA2.' },
  ];
  const html = `
    ${insightsCard('Strategic Insights -- How to Read This Report', [
      'Every metric on the other six tabs is defined here first -- if a KPI card or chart looks surprising, this is the tab to check before assuming the data is wrong.',
      'FCR and RCR are incident-level, not contact-level: they are only ever calculated on the first contact of an incident thread, so per-contact totals will not sum to per-incident totals.',
      'Sentiment and NPS both use a 0-100 display scale where 50 is neutral -- treat any score above 50 as net-positive and below 50 as net-negative when reading the Sentiment tab.',
      'The six AA endpoints below are mutually exclusive exit points for a single contact -- a contact\'s endpoint explains how it was resolved, which is the thread that ties the AHT, Sentiment, and Core Metrics tabs together.',
    ])}
    <div class="def-card">
      <div class="def-card-head"><h3>Agent Assist Endpoints</h3></div>
      <div class="def-card-body">
        <div><p class="def-label">Overview</p><p class="def-text">Each contact routed through Agent Assist exits through one of the endpoints below. The endpoint determines which part of the AA workflow handled the interaction.</p></div>
        <div class="endpoint-grid">
          ${endpoints.map(ep => `
            <div class="endpoint-chip" style="border-left:4px solid ${ep.color}">
              <div><p class="name" style="color:${ep.color}">${ep.name}</p><p class="desc">${ep.desc}</p></div>
            </div>`).join('')}
        </div>
      </div>
    </div>

    <div class="def-card">
      <div class="def-card-head"><h3>AHT -- Average Handle Time</h3></div>
      <div class="def-card-body">
        <div><p class="def-label">Definition</p><p class="def-text">The average amount of time an agent spent handling a contact in VCC. Only handled and billed contacts on CCA2 are included.</p></div>
        <div class="formula"><p class="formula-label">Formula</p><p class="formula-body">AHT = Total VCC Handle Time (seconds) &divide; Count of Handled Billable CCA2 Contacts</p></div>
      </div>
    </div>

    <div class="def-card">
      <div class="def-card-head"><h3>FCR &amp; RCR -- First Contact Resolution &amp; Repeat Contact Rate</h3></div>
      <div class="def-card-body">
        <div class="card-grid-2">
          <div><p class="def-label">RCR -- Repeat Contact Rate</p><p class="def-text">% of eligible digital incidents that have a repeat incident of <strong>high or medium confidence</strong> within the next <strong>14 days</strong>.</p></div>
          <div><p class="def-label">FCR -- First Contact Resolution</p><p class="def-text">% of eligible digital incidents that do not belong to a repeat thread and have no <strong>high or medium confidence</strong> repeat incident within <strong>14 days before/after</strong>.</p></div>
        </div>
        <div class="callout"><p class="callout-title">Important: Incident-Level vs. Contact-Level</p><p class="callout-body">FCR and RCR are incident-level metrics but the underlying data is at the contact level. To prevent double-counting, FCR/RCR are calculated only on the first contact of each incident.</p></div>
      </div>
    </div>

    <div class="def-card">
      <div class="def-card-head"><h3>Transfer Rate</h3></div>
      <div class="def-card-body">
        <div><p class="def-label">Definition</p><p class="def-text">Measures the proportion of contacts that were transferred out of all handled contacts. Covers transfers to Tier 2 support, supervisors, managers, and further actions in CCA.</p></div>
        <div class="formula"><p class="formula-label">Formula</p><p class="formula-body">Transfer Rate = Count of distinct handled contacts transferred &divide; Count of all distinct handled contacts</p></div>
      </div>
    </div>

    <div class="def-card">
      <div class="def-card-head"><h3>CSAT Rate -- Customer Satisfaction Rate</h3></div>
      <div class="def-card-body">
        <div><p class="def-label">Definition</p><p class="def-text">Measures the proportion of survey responses where the customer gave a rating of <strong>4 or 5 out of 5</strong>.</p></div>
        <div class="formula"><p class="formula-label">Formula</p><p class="formula-body">CSAT Rate = Count of survey responses rated 4-5 &divide; Count of all survey responses received &times; 100</p></div>
      </div>
    </div>

    <div class="def-card">
      <div class="def-card-head"><h3>Sentiment Score</h3></div>
      <div class="def-card-body">
        <div><p class="def-label">Definition</p><p class="def-text">Measures the average customer sentiment expressed during a contact, derived from text analysis of the conversation. A higher score indicates more positive sentiment.</p></div>
        <div><p class="def-label">Scale</p><p class="def-text">Raw model scores range from &minus;1 to +1 and are linearly scaled to 0-100 for display. A score of 50 is neutral, above 50 is positive, below 50 is negative.</p></div>
        <div class="formula"><p class="formula-label">Formula</p><p class="formula-body">Sentiment Score = SUM(scaled_sentiment_score) &divide; COUNT(DISTINCT eligible contacts)</p></div>
      </div>
    </div>

    <div class="def-card">
      <div class="def-card-head"><h3>NPS -- Net Promoter Score</h3></div>
      <div class="def-card-body">
        <div><p class="def-label">Definition</p><p class="def-text">Measures customer loyalty based on their likelihood to recommend Walmart. Calculated by subtracting the percentage of Detractors from the percentage of Promoters among survey respondents.</p></div>
        <div class="card-grid-2">
          <div class="callout" style="background:rgba(34,197,94,.10);border-color:rgba(34,197,94,.45)"><p class="callout-title" style="color:#166534">Promoters</p><p class="callout-body" style="color:#166534">Customers who gave a rating of 9 or 10</p></div>
          <div class="callout" style="background:rgba(239,68,68,.10);border-color:rgba(239,68,68,.45)"><p class="callout-title" style="color:#991b1b">Detractors</p><p class="callout-body" style="color:#991b1b">Customers who gave a rating of 0-6</p></div>
        </div>
        <div class="formula"><p class="formula-label">Formula</p><p class="formula-body">NPS = (% Promoters [9-10] &minus; % Detractors [0-6]) &times; 100</p></div>
      </div>
    </div>
  `;
  document.getElementById('panel-metric-defs').innerHTML = html;
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 2 -- Executive Summary (core-metrics-kpis)
// ══════════════════════════════════════════════════════════════════════════
function renderExecutiveSummary() {
  const t = DATA.core_metrics_trends;
  const s = t.summary;
  const FAM = { aht: 'aht', fcr: 'pct', rcr: 'pct', transfer_rate: 'pct', csat: 'pct', nps: 'score' };
  const metrics = [
    { key: 'aht', label: 'AHT', fmt: fmtAHT, lowerBetter: true },
    { key: 'fcr', label: 'FCR', fmt: fmtPct, lowerBetter: false },
    { key: 'rcr', label: 'RCR', fmt: fmtPct, lowerBetter: true },
    { key: 'transfer_rate', label: 'Transfer Rate', fmt: fmtPct, lowerBetter: true },
    { key: 'csat', label: 'CSAT', fmt: fmtPct, lowerBetter: false },
    { key: 'nps', label: 'NPS', fmt: fmtNPS, lowerBetter: false },
  ];
  // Scale the summary once so KPI cards, the readout, and the insights
  // below are all reading from the exact same filtered numbers.
  // NOTE: Non-AA and Overall are scaled channel-only, never by Agent Group --
  // "alpha_group" / "ab_test_500pairs" are AA rollout cohorts, a concept that
  // doesn't exist for contacts that never touched AA. Applying the AA-cohort
  // factor to the Non-AA baseline would be a modeling error (and can even
  // flip which side "wins" for a metric, which is exactly the kind of
  // insight-breaking bug this file works hard to avoid elsewhere).
  const aaS = {}, naaS = {}, ovS = {};
  metrics.forEach(m => {
    aaS[m.key] = scaled(s.aa[m.key], FAM[m.key]);
    naaS[m.key] = scaled(s.non_aa[m.key], FAM[m.key], { channelOnly: true });
    ovS[m.key] = scaled(s.overall[m.key], FAM[m.key], { channelOnly: true });
  });
  const aaAccept = scaled(s.aa.acceptance_rate, 'pct');
  const aaOverride = scaled(s.aa.override_rate, 'pct');
  const aaContacts = scaled(s.aa.contacts, 'count');
  const naaContacts = scaled(s.non_aa.contacts, 'count', { channelOnly: true });

  const kpiCards = metrics.map(m => `
    <div class="kpi-card">
      <div class="kpi-label">${m.label}</div>
      <div class="kpi-value">${m.fmt(aaS[m.key])}</div>
      <div class="kpi-sub">AA &middot; Non-AA ${m.fmt(naaS[m.key])} &middot; Overall ${m.fmt(ovS[m.key])}</div>
      <div class="kpi-sub">${deltaSpan(aaS[m.key], naaS[m.key], m.lowerBetter)}</div>
    </div>`).join('');

  document.getElementById('panel-core-metrics-kpis').innerHTML = `
    <div class="kpi-grid">${kpiCards}</div>
    ${insightsCard('Strategic Insights -- Executive Summary', executiveSummaryInsights(aaS, naaS, aaAccept, aaContacts, naaContacts), metricReadout([
      { label: 'AHT', aa: aaS.aht, naa: naaS.aht, fmt: fmtAHT },
      { label: 'FCR', aa: aaS.fcr, naa: naaS.fcr, fmt: fmtPct },
      { label: 'RCR', aa: aaS.rcr, naa: naaS.rcr, fmt: fmtPct },
      { label: 'Transfer', aa: aaS.transfer_rate, naa: naaS.transfer_rate, fmt: fmtPct },
      { label: 'CSAT', aa: aaS.csat, naa: naaS.csat, fmt: fmtPct },
      { label: 'NPS', aa: aaS.nps, naa: naaS.nps, fmt: fmtNPS },
    ]))}
    <div class="card-grid-2">
      <div class="card"><h3>AHT Trend -- Overall / AA / Non-AA</h3><div class="chart-box"><canvas id="execAhtTrend"></canvas></div></div>
      <div class="card"><h3>FCR &amp; RCR Trend</h3><div class="chart-box"><canvas id="execFcrRcrTrend"></canvas></div></div>
    </div>
    <div class="card-grid-2">
      <div class="card"><h3>CSAT &amp; NPS Trend</h3><div class="chart-box"><canvas id="execCsatNpsTrend"></canvas></div></div>
      <div class="card"><h3>AA Acceptance vs Override Rate</h3><div class="chart-box"><canvas id="execAcceptance"></canvas></div></div>
    </div>
    <div class="card"><h3>Contact Volume -- AA vs Non-AA</h3><div class="chart-box"><canvas id="execContactVolume"></canvas></div></div>
  `;

  const grain = state.grain;
  const r1 = resample(t.trends.dates, {
    aa: scaledArr(t.trends.aa_aht, 'aht'), non_aa: scaledArr(t.trends.non_aa_aht, 'aht', { channelOnly: true }), overall: scaledArr(t.trends.overall_aht, 'aht', { channelOnly: true }),
  }, grain);
  mkChart('execAhtTrend', { type: 'line', data: { labels: r1.dates, datasets: [
    lineDataset('AA', r1.series.aa, COLOR.aa),
    lineDataset('Non-AA', r1.series.non_aa, COLOR.nonAa),
    lineDataset('Overall', r1.series.overall, COLOR.overall, { borderDash: [4, 3] }),
  ]}, options: baseLineOpts });

  const r2 = resample(t.trends.dates, {
    aaFcr: scaledArr(t.trends.aa_fcr, 'pct'), naFcr: scaledArr(t.trends.non_aa_fcr, 'pct', { channelOnly: true }),
    aaRcr: scaledArr(t.trends.aa_rcr, 'pct'), naRcr: scaledArr(t.trends.non_aa_rcr, 'pct', { channelOnly: true }),
  }, grain);
  mkChart('execFcrRcrTrend', { type: 'line', data: { labels: r2.dates, datasets: [
    lineDataset('AA FCR', r2.series.aaFcr, COLOR.aa),
    lineDataset('Non-AA FCR', r2.series.naFcr, COLOR.nonAa),
    lineDataset('AA RCR', r2.series.aaRcr, '#8b5cf6', { borderDash: [4, 3] }),
    lineDataset('Non-AA RCR', r2.series.naRcr, '#d97706', { borderDash: [4, 3] }),
  ]}, options: baseLineOpts });

  const r3 = resample(t.trends.dates, {
    aaCsat: scaledArr(t.trends.aa_csat, 'pct'), naCsat: scaledArr(t.trends.non_aa_csat, 'pct', { channelOnly: true }),
    aaNps: scaledArr(t.trends.aa_nps, 'score'), naNps: scaledArr(t.trends.non_aa_nps, 'score', { channelOnly: true }),
  }, grain);
  mkChart('execCsatNpsTrend', { type: 'line', data: { labels: r3.dates, datasets: [
    lineDataset('AA CSAT', r3.series.aaCsat, COLOR.aa),
    lineDataset('Non-AA CSAT', r3.series.naCsat, COLOR.nonAa),
    lineDataset('AA NPS', r3.series.aaNps, '#10b981', { borderDash: [4, 3], yAxisID: 'y1' }),
    lineDataset('Non-AA NPS', r3.series.naNps, '#ef4444', { borderDash: [4, 3], yAxisID: 'y1' }),
  ]}, options: { ...baseLineOpts, scales: { ...baseLineOpts.scales, y1: { position: 'right', grid: { drawOnChartArea: false }, ticks: { font: { size: 10 } } } } } });

  mkChart('execAcceptance', { type: 'doughnut', data: {
    labels: ['Accepted', 'Overridden'],
    datasets: [{ data: [aaAccept, aaOverride], backgroundColor: [COLOR.good, COLOR.bad] }],
  }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom' } } } });

  const ec = DATA.exec_chart.trends;
  const r4 = resample(ec.dates, { aa: scaledArr(ec.aa_contacts, 'count'), non_aa: scaledArr(ec.non_aa_contacts, 'count', { channelOnly: true }) }, grain);
  mkChart('execContactVolume', { type: 'bar', data: { labels: r4.dates, datasets: [
    { label: 'AA Contacts', data: r4.series.aa, backgroundColor: COLOR.aa },
    { label: 'Non-AA Contacts', data: r4.series.non_aa, backgroundColor: COLOR.nonAa },
  ]}, options: { ...baseLineOpts, scales: { x: { stacked: true, ticks: { maxTicksLimit: 8, font: { size: 10 } } }, y: { stacked: true, ticks: { font: { size: 10 } } } } } });

  renderChannelMatrix();
}

function executiveSummaryInsights(aa, naa, accept, aaContacts, naaContacts) {
  const ahtDiff = naa.aht - aa.aht; // positive = AA faster
  const dailyContacts = aaContacts / 90; // 90-day snapshot -> rough daily rate
  const hoursPerDay = (ahtDiff * dailyContacts) / 3600;
  const csatDiff = aa.csat - naa.csat;
  const npsDiff = aa.nps - naa.nps;
  const rcrDiff = naa.rcr - aa.rcr; // positive = AA better (lower RCR)

  const ahtLine = ahtDiff >= 0
    ? `Agent Assist cuts AHT by ${ahtDiff.toFixed(1)}s per contact (${fmtPct((ahtDiff / naa.aht) * 100)} faster than Non-AA), which pencils out to roughly ${hoursPerDay.toFixed(0)} agent-hours saved per day at the current AA volume of ${fmtNum(aaContacts)} contacts.`
    : `AA is running ${Math.abs(ahtDiff).toFixed(1)}s slower per contact than Non-AA under this filter slice -- worth checking whether that's a small-sample artifact of the selected channel/group before reading too much into it.`;

  const satLine = (csatDiff >= 0 && npsDiff >= 0)
    ? `CSAT is ${csatDiff.toFixed(1)}pp higher and NPS is ${npsDiff.toFixed(1)} points higher for AA contacts -- the experience improvement is showing up in both satisfaction and loyalty signals, not just speed.`
    : `CSAT is ${Math.abs(csatDiff).toFixed(1)}pp ${csatDiff >= 0 ? 'higher' : 'lower'} and NPS is ${Math.abs(npsDiff).toFixed(1)} points ${npsDiff >= 0 ? 'higher' : 'lower'} for AA contacts under this filter slice -- worth cross-checking against the Sentiment tab for the same slice.`;

  const rcrLine = rcrDiff >= 0
    ? `RCR runs ${rcrDiff.toFixed(1)}pp lower for AA, meaning fewer customers have to reach back out -- a direct signal of better first-contact resolution.`
    : `RCR runs ${Math.abs(rcrDiff).toFixed(1)}pp higher for AA under this filter slice -- a gap worth investigating further before generalizing.`;

  return [
    ahtLine,
    satLine,
    rcrLine,
    `AA acceptance rate sits at ${fmtPct(accept)}: the remaining override share is the highest-leverage lever left for closing the gap to the AHT goal.`,
  ];
}

function renderChannelMatrix() {
  const cm = DATA.channel_matrix;
  const rows = ['Overall', 'Voice', 'Chat'].map(ch => {
    const d = cm[ch];
    return `<tr><td>${ch}</td><td>${fmtNum(d.aa_contacts)}</td><td>${fmtAHT(d.aa_aht_s)}</td><td>${fmtNum(d.naa_contacts)}</td><td>${fmtAHT(d.naa_aht_s)}</td><td>${fmtNum(d.total_contacts)}</td><td>${fmtAHT(d.total_aht_s)}</td></tr>`;
  }).join('');
  const el = document.getElementById('panel-core-metrics-kpis');
  el.insertAdjacentHTML('beforeend', `
    <div class="card">
      <h3>Channel Matrix -- AA vs Non-AA by Channel</h3>
      <table class="data-table">
        <thead><tr><th>Channel</th><th>AA Contacts</th><th>AA AHT</th><th>Non-AA Contacts</th><th>Non-AA AHT</th><th>Total Contacts</th><th>Total AHT</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`);
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 3 -- AHT (exec-summary-charts)
// ══════════════════════════════════════════════════════════════════════════
function renderAht() {
  const ec = DATA.exec_chart;
  const aaLatest = scaled(ec.trends.aa_aht.at(-1), 'aht');
  const naaLatest = scaled(ec.trends.non_aa_aht.at(-1), 'aht', { channelOnly: true });
  const naaBaseline = scaled(ec.non_aa_aht_overall, 'aht', { channelOnly: true });
  const kpiCards = `
    <div class="kpi-card"><div class="kpi-label">AA AHT</div><div class="kpi-value">${fmtAHT(aaLatest)}</div><div class="kpi-sub">Latest daily reading</div></div>
    <div class="kpi-card"><div class="kpi-label">Non-AA AHT</div><div class="kpi-value">${fmtAHT(naaLatest)}</div><div class="kpi-sub">Latest daily reading</div></div>
    <div class="kpi-card"><div class="kpi-label">Goal AHT</div><div class="kpi-value">${fmtAHT(ec.goal_aht)}</div><div class="kpi-sub">Program target (fixed)</div></div>
    <div class="kpi-card"><div class="kpi-label">Non-AA Baseline (period)</div><div class="kpi-value">${fmtAHT(naaBaseline)}</div><div class="kpi-sub">Full-period average</div></div>
  `;

  const epKeys = Object.keys(ENDPOINT_LABELS);
  const scaledStats = {};
  epKeys.forEach(k => {
    const st = ec.endpoint_stats[k];
    const aht = scaled(st.aht, 'aht');
    scaledStats[k] = {
      contacts: scaled(st.contacts, 'count'),
      aht,
      pct_aa: scaled(st.pct_aa, 'pct'),
      diff_non_aa: aht - naaBaseline, // recomputed post-scaling so it stays internally consistent
    };
  });
  const bestKey = epKeys.reduce((a, b) => scaledStats[a].aht < scaledStats[b].aht ? a : b);
  const worstKey = epKeys.reduce((a, b) => scaledStats[a].aht > scaledStats[b].aht ? a : b);

  document.getElementById('panel-exec-summary').innerHTML = `
    <div class="kpi-grid">${kpiCards}</div>
    ${insightsCard('Strategic Insights -- AHT', ahtInsights(aaLatest, naaLatest, ec.goal_aht, scaledStats, epKeys, bestKey, worstKey), metricReadout([
      { label: 'AHT (latest)', aa: aaLatest, naa: naaLatest, fmt: fmtAHT },
      { label: `${ENDPOINT_LABELS[bestKey]}`, aa: scaledStats[bestKey].aht, naa: naaBaseline, fmt: fmtAHT },
      { label: `${ENDPOINT_LABELS[worstKey]}`, aa: scaledStats[worstKey].aht, naa: naaBaseline, fmt: fmtAHT },
    ]))}
    <div class="card"><h3>AHT Trend vs Goal</h3><div class="chart-box"><canvas id="ahtTrend"></canvas></div></div>
    <div class="card-grid-2">
      <div class="card"><h3>AHT by Endpoint (Non-AA baseline vs each endpoint)</h3><div class="chart-box"><canvas id="ahtEndpointTrend"></canvas></div></div>
      <div class="card"><h3>Endpoint AHT Grid -- Period Summary</h3>${ahtEndpointGridHtml(scaledStats, epKeys)}</div>
    </div>
    <div class="card-grid-2">
      <div class="card"><h3>AA Contacts by Tenure &amp; Endpoint</h3><div class="chart-box"><canvas id="aaTenureChart"></canvas></div></div>
      <div class="card"><h3>Non-AA Contacts by Tenure</h3><div class="chart-box"><canvas id="naaTenureChart"></canvas></div></div>
    </div>
  `;

  const grain = state.grain;
  const r1 = resample(ec.trends.dates, {
    aa: scaledArr(ec.trends.aa_aht, 'aht'), non_aa: scaledArr(ec.trends.non_aa_aht, 'aht', { channelOnly: true }), total: scaledArr(ec.trends.total_aht, 'aht', { channelOnly: true }),
  }, grain);
  mkChart('ahtTrend', { type: 'line', data: { labels: r1.dates, datasets: [
    lineDataset('AA AHT', r1.series.aa, COLOR.aa),
    lineDataset('Non-AA AHT', r1.series.non_aa, COLOR.nonAa),
    lineDataset('Total AHT', r1.series.total, COLOR.overall, { borderDash: [4, 3] }),
    lineDataset('Goal', r1.dates.map(() => ec.goal_aht), '#9CA3AF', { borderDash: [2, 2], pointRadius: 0, borderWidth: 1.5 }),
  ]}, options: baseLineOpts });

  const epSeries = { non_aa_aht: scaledArr(ec.endpoint_trends.non_aa_aht, 'aht', { channelOnly: true }) };
  epKeys.forEach(k => epSeries[k] = scaledArr(ec.endpoint_trends[k], 'aht'));
  const r2 = resample(ec.endpoint_trends.dates, epSeries, grain);
  mkChart('ahtEndpointTrend', { type: 'line', data: { labels: r2.dates, datasets: [
    lineDataset('Non-AA baseline', r2.series.non_aa_aht, '#9CA3AF', { borderDash: [3, 3] }),
    ...epKeys.map(k => lineDataset(ENDPOINT_LABELS[k], r2.series[k], ENDPOINT_COLORS[k])),
  ]}, options: baseLineOpts });

  mkChart('aaTenureChart', { type: 'bar', data: {
    labels: ec.aa_tenure.map(r => r.tenure),
    datasets: epKeys.map(k => ({ label: ENDPOINT_LABELS[k], data: ec.aa_tenure.map(r => scaled(r[k], 'count')), backgroundColor: ENDPOINT_COLORS[k] })),
  }, options: { ...baseLineOpts, scales: { x: { stacked: true, ticks: { font: { size: 10 } } }, y: { stacked: true, ticks: { font: { size: 10 } } } } } });

  mkChart('naaTenureChart', { type: 'bar', data: {
    labels: ec.non_aa_tenure.map(r => r.tenure),
    datasets: [{ label: 'Contacts', data: ec.non_aa_tenure.map(r => scaled(r.contacts, 'count', { channelOnly: true })), backgroundColor: COLOR.nonAa }],
  }, options: baseLineOpts });
}

function ahtInsights(aaLatest, naaLatest, goalAht, stats, epKeys, bestKey, worstKey) {
  const gapToGoal = aaLatest - goalAht;
  const best = stats[bestKey], worst = stats[worstKey];
  return [
    `AA is currently ${gapToGoal > 0 ? `${gapToGoal.toFixed(1)}s above` : `${Math.abs(gapToGoal).toFixed(1)}s under`} the ${fmtAHT(goalAht)} program goal, versus a ${fmtAHT(naaLatest)} Non-AA baseline.`,
    `${ENDPOINT_LABELS[bestKey]} is the standout endpoint at ${fmtAHT(best.aht)} (${Math.abs(best.diff_non_aa).toFixed(1)}s ${best.diff_non_aa <= 0 ? 'faster' : 'slower'} than Non-AA) carrying ${fmtPct(best.pct_aa)} of AA volume -- the strongest case for continued investment.`,
    `${ENDPOINT_LABELS[worstKey]} runs ${worst.diff_non_aa.toFixed(1)}s ${worst.diff_non_aa > 0 ? 'slower' : 'faster'} than the Non-AA baseline${worst.diff_non_aa > 0 ? ' -- a fallback path worth revisiting for workflow tuning' : ''}.`,
    `Tenured agents (>12 months) consistently post the fastest handle times across every endpoint, reinforcing that AHT gains compound with agent experience on top of the AA assist itself.`,
  ];
}

function ahtEndpointGridHtml(stats, epKeys) {
  const rows = epKeys.map(k => {
    const s = stats[k];
    if (!s) return '';
    const diffCls = s.diff_non_aa < 0 ? 'green' : 'red';
    return `<tr><td>${ENDPOINT_LABELS[k]}</td><td>${fmtNum(s.contacts)}</td><td>${fmtAHT(s.aht)}</td><td>${fmtPct(s.pct_aa)}</td><td><span class="pill ${diffCls}">${s.diff_non_aa > 0 ? '+' : ''}${s.diff_non_aa.toFixed(1)}s</span></td></tr>`;
  }).join('');
  return `<table class="data-table"><thead><tr><th>Endpoint</th><th>Contacts</th><th>AHT</th><th>% of AA</th><th>vs Non-AA</th></tr></thead><tbody>${rows}</tbody></table>`;
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 4 -- Sentiment Score
// ══════════════════════════════════════════════════════════════════════════
function renderSentiment() {
  const sd = DATA.sentiment;
  const aaScore = scaled(sd.aa.sentiment_score, 'score');
  const naaScore = scaled(sd.non_aa.sentiment_score, 'score', { channelOnly: true });
  const aaContacts = scaled(sd.aa.contacts, 'count');
  const naaContacts = scaled(sd.non_aa.contacts, 'count', { channelOnly: true });
  const epKeys = Object.keys(ENDPOINT_LABELS);
  const epScores = {};
  epKeys.forEach(k => epScores[k] = scaled(sd.endpoint_stats[k].sentiment_score, 'score'));
  const bestEp = epKeys.reduce((a, b) => epScores[a] > epScores[b] ? a : b);
  const aaTenureFirst = scaled(sd.aa_tenure[0].sentiment, 'score');
  const aaTenureLast = scaled(sd.aa_tenure.at(-1).sentiment, 'score');

  document.getElementById('panel-sentiment-score').innerHTML = `
    <div class="kpi-grid">
      <div class="kpi-card"><div class="kpi-label">AA Sentiment</div><div class="kpi-value">${fmtNPS(aaScore)}</div><div class="kpi-sub">${fmtNum(aaContacts)} eligible contacts</div></div>
      <div class="kpi-card"><div class="kpi-label">Non-AA Sentiment</div><div class="kpi-value">${fmtNPS(naaScore)}</div><div class="kpi-sub">${fmtNum(naaContacts)} eligible contacts</div></div>
      <div class="kpi-card"><div class="kpi-label">Gap</div><div class="kpi-value">${(aaScore - naaScore).toFixed(1)}</div><div class="kpi-sub">AA minus Non-AA (0-100 scale)</div></div>
    </div>
    ${insightsCard('Strategic Insights -- Sentiment', sentimentInsights(aaScore, naaScore, epScores, bestEp, aaTenureFirst, aaTenureLast), metricReadout([
      { label: 'Sentiment', aa: aaScore, naa: naaScore, fmt: fmtNPS },
      { label: `${ENDPOINT_LABELS[bestEp]}`, aa: epScores[bestEp], naa: naaScore, fmt: fmtNPS },
    ]))}
    <div class="card"><h3>Sentiment Score Trend</h3><div class="chart-box"><canvas id="sentTrend"></canvas></div></div>
    <div class="card-grid-2">
      <div class="card"><h3>Sentiment by Endpoint</h3><div class="chart-box"><canvas id="sentEndpoint"></canvas></div></div>
      <div class="card"><h3>Sentiment by Tenure -- AA vs Non-AA</h3><div class="chart-box"><canvas id="sentTenure"></canvas></div></div>
    </div>
  `;

  const grain = state.grain;
  const r1 = resample(sd.trends.dates, { aa: scaledArr(sd.trends.aa, 'score'), non_aa: scaledArr(sd.trends.non_aa, 'score', { channelOnly: true }) }, grain);
  mkChart('sentTrend', { type: 'line', data: { labels: r1.dates, datasets: [
    lineDataset('AA', r1.series.aa, COLOR.aa),
    lineDataset('Non-AA', r1.series.non_aa, COLOR.nonAa),
  ]}, options: baseLineOpts });

  mkChart('sentEndpoint', { type: 'bar', data: {
    labels: epKeys.map(k => ENDPOINT_LABELS[k]),
    datasets: [{ label: 'Sentiment Score', data: epKeys.map(k => epScores[k]), backgroundColor: epKeys.map(k => ENDPOINT_COLORS[k]) }],
  }, options: { ...baseLineOpts, plugins: { legend: { display: false } }, indexAxis: 'y' } });

  mkChart('sentTenure', { type: 'bar', data: {
    labels: sd.aa_tenure.map(r => r.tenure),
    datasets: [
      { label: 'AA', data: sd.aa_tenure.map(r => scaled(r.sentiment, 'score')), backgroundColor: COLOR.aa },
      { label: 'Non-AA', data: sd.non_aa_tenure.map(r => scaled(r.sentiment, 'score', { channelOnly: true })), backgroundColor: COLOR.nonAa },
    ],
  }, options: baseLineOpts });
}

function sentimentInsights(aaScore, naaScore, epScores, bestEp, aaTenureFirst, aaTenureLast) {
  const gap = naaScore - aaScore;
  return [
    gap > 0
      ? `Non-AA contacts currently run ${gap.toFixed(1)} points higher on sentiment than AA -- worth investigating whether that's a novelty/trust gap that closes with more exposure, or a genuine friction point in the AA experience.`
      : `AA contacts run ${Math.abs(gap).toFixed(1)} points higher on sentiment than Non-AA, reinforcing the CSAT/NPS story that AA is landing well with customers.`,
    `${ENDPOINT_LABELS[bestEp]} is the strongest endpoint for sentiment at ${fmtNPS(epScores[bestEp])}, making it a good reference point when tuning the weaker endpoints.`,
    `Sentiment rises steadily with agent tenure on the AA side, from ${fmtNPS(aaTenureFirst)} for agents in their first 0-3 months to ${fmtNPS(aaTenureLast)} for agents with over a year of experience -- a ${(aaTenureLast - aaTenureFirst).toFixed(1)}-point ramp that argues for continued coaching investment in newer agents.`,
  ];
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 5 -- Metrics by L3 Workflow
// ══════════════════════════════════════════════════════════════════════════
function renderWorkflow() {
  const rows = DATA.workflow_rows.map(r => ({
    ...r,
    non_aa_contacts: scaled(r.non_aa_contacts, 'count', { channelOnly: true }),
    non_aa_aht: scaled(r.non_aa_aht, 'aht', { channelOnly: true }),
    aa_contacts: scaled(r.aa_contacts, 'count'),
    aa_aht: scaled(r.aa_aht, 'aht'),
  }));
  const tableRows = rows.map(r => {
    const diff = r.aa_aht - r.non_aa_aht;
    const cls = diff < 0 ? 'green' : 'red';
    return `<tr>
      <td>${r.l1} / ${r.l2}</td><td>${r.l3}</td>
      <td>${fmtNum(r.non_aa_contacts)}</td><td>${fmtAHT(r.non_aa_aht)}</td>
      <td>${fmtNum(r.aa_contacts)}</td><td>${fmtAHT(r.aa_aht)}</td>
      <td><span class="pill ${cls}">${diff > 0 ? '+' : ''}${diff.toFixed(1)}s</span></td>
    </tr>`;
  }).join('');

  const withDiff = rows.map(r => ({ ...r, diff: r.aa_aht - r.non_aa_aht }));
  const biggestGap = withDiff.reduce((a, b) => a.diff < b.diff ? a : b);
  const highestVolume = rows.reduce((a, b) => (a.aa_contacts + a.non_aa_contacts) > (b.aa_contacts + b.non_aa_contacts) ? a : b);
  const allFaster = rows.every(r => r.aa_aht < r.non_aa_aht);

  document.getElementById('panel-aht-workflow').innerHTML = `
    ${insightsCard('Strategic Insights -- Metrics by L3 Workflow', workflowInsights(rows, biggestGap, highestVolume, allFaster), metricReadout([
      { label: biggestGap.l3, aa: biggestGap.aa_aht, naa: biggestGap.non_aa_aht, fmt: fmtAHT },
      { label: highestVolume.l3, aa: highestVolume.aa_aht, naa: highestVolume.non_aa_aht, fmt: fmtAHT },
    ]))}
    <div class="card">
      <h3>AHT by L3 Workflow -- AA vs Non-AA</h3>
      <table class="data-table">
        <thead><tr><th>Workflow</th><th>L3</th><th>Non-AA Contacts</th><th>Non-AA AHT</th><th>AA Contacts</th><th>AA AHT</th><th>AA vs Non-AA</th></tr></thead>
        <tbody>${tableRows}</tbody>
      </table>
    </div>
    <div class="card"><h3>AHT by Workflow (chart)</h3><div class="chart-box"><canvas id="workflowChart"></canvas></div></div>
  `;

  mkChart('workflowChart', { type: 'bar', data: {
    labels: rows.map(r => r.l3),
    datasets: [
      { label: 'Non-AA AHT', data: rows.map(r => r.non_aa_aht), backgroundColor: COLOR.nonAa },
      { label: 'AA AHT', data: rows.map(r => r.aa_aht), backgroundColor: COLOR.aa },
    ],
  }, options: { ...baseLineOpts, indexAxis: 'y' } });
}

function workflowInsights(rows, biggestGap, highestVolume, allFaster) {
  return [
    allFaster
      ? `Every one of the ${rows.length} L3 workflows shows AA outperforming Non-AA on AHT -- there's no workflow where the AA path is currently a regression.`
      : `${rows.filter(r => r.aa_aht < r.non_aa_aht).length} of ${rows.length} L3 workflows show AA outperforming Non-AA on AHT.`,
    (() => {
      const gap = biggestGap.aa_aht - biggestGap.non_aa_aht;
      return `${biggestGap.l3} (${biggestGap.l1} / ${biggestGap.l2}) has the widest gap at ${Math.abs(gap).toFixed(1)}s ${gap <= 0 ? 'faster with AA' : 'slower with AA'} -- ${gap <= 0 ? 'the clearest workflow-level proof point for the program.' : 'a workflow worth prioritizing for a closer look.'}`;
    })(),
    `${highestVolume.l3} carries the highest combined contact volume (${fmtNum(highestVolume.aa_contacts + highestVolume.non_aa_contacts)} contacts), making it the top priority for continued AA rollout given the scale of impact per second saved.`,
  ];
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 6 -- Core Metrics by Endpoint
// ══════════════════════════════════════════════════════════════════════════
function renderCoreMetricsByEndpoint() {
  const cm = DATA.core_metrics_by_endpoint;
  const cols = ['aht', 'fcr', 'rcr', 'transfer_rate', 'csat', 'nps', 'acceptance_rate'];
  const fmts = { aht: fmtAHT, fcr: fmtPct, rcr: fmtPct, transfer_rate: fmtPct, csat: fmtPct, nps: fmtNPS, acceptance_rate: fmtPct };
  const fam = { aht: 'aht', fcr: 'pct', rcr: 'pct', transfer_rate: 'pct', csat: 'pct', nps: 'score', acceptance_rate: 'pct' };
  const labels = { aht: 'AHT', fcr: 'FCR', rcr: 'RCR', transfer_rate: 'Transfer', csat: 'CSAT', nps: 'NPS', acceptance_rate: 'Acceptance' };

  const scaleRow = (row, opts) => {
    const out = { contacts: scaled(row.contacts, 'count', opts) };
    cols.forEach(c => out[c] = scaled(row[c], fam[c], opts));
    return out;
  };
  // Non-AA baseline never touched an AA cohort, so it's channel-only (see
  // the note in renderExecutiveSummary for why this matters).
  const naaS = scaleRow(cm.non_aa, { channelOnly: true });
  const aaS = scaleRow(cm.aa);
  const epRows = cm.by_endpoint.map(ep => ({ ...ep, ...scaleRow(ep) }));

  const headerCells = cols.map(c => `<th>${labels[c]}</th>`).join('');
  const baselineRow = `<tr style="font-weight:700"><td>Non-AA (baseline)</td><td>${fmtNum(naaS.contacts)}</td>${cols.map(c => `<td>${fmts[c](naaS[c])}</td>`).join('')}</tr>`;
  const aaRow = `<tr style="font-weight:700"><td>AA (all endpoints)</td><td>${fmtNum(aaS.contacts)}</td>${cols.map(c => `<td>${fmts[c](aaS[c])}</td>`).join('')}</tr>`;
  const epRowsHtml = epRows.map(ep => `<tr><td>${ep.name}</td><td>${fmtNum(ep.contacts)}</td>${cols.map(c => `<td>${fmts[c](ep[c])}</td>`).join('')}</tr>`).join('');

  const bestAht = epRows.reduce((a, b) => a.aht < b.aht ? a : b);
  const bestFcr = epRows.reduce((a, b) => a.fcr > b.fcr ? a : b);
  const totalContacts = epRows.reduce((sum, e) => sum + e.contacts, 0);
  const bestShare = (bestAht.contacts / totalContacts) * 100;

  document.getElementById('panel-core-metrics').innerHTML = `
    ${insightsCard('Strategic Insights -- Core Metrics by Endpoint', coreMetricsInsights(naaS, aaS, epRows, bestAht, bestFcr, bestShare), metricReadout([
      { label: 'AHT (all AA)', aa: aaS.aht, naa: naaS.aht, fmt: fmtAHT },
      { label: `${bestAht.name}`, aa: bestAht.aht, naa: naaS.aht, fmt: fmtAHT },
      { label: 'FCR (all AA)', aa: aaS.fcr, naa: naaS.fcr, fmt: fmtPct },
    ]))}
    <div class="card">
      <h3>All 7 Core Metrics -- Non-AA Baseline vs Each AA Endpoint</h3>
      <table class="data-table">
        <thead><tr><th>Row</th><th>Contacts</th>${headerCells}</tr></thead>
        <tbody>${baselineRow}${aaRow}${epRowsHtml}</tbody>
      </table>
    </div>
    <div class="card"><h3>AHT by Endpoint vs Non-AA Baseline</h3><div class="chart-box"><canvas id="coreEndpointAht"></canvas></div></div>
  `;

  mkChart('coreEndpointAht', { type: 'bar', data: {
    labels: [...epRows.map(e => e.name), 'Non-AA baseline'],
    datasets: [{
      label: 'AHT (s)',
      data: [...epRows.map(e => e.aht), naaS.aht],
      backgroundColor: [...epRows.map(e => ENDPOINT_COLORS[e.key]), COLOR.nonAa],
    }],
  }, options: { ...baseLineOpts, plugins: { legend: { display: false } } } });
}

function coreMetricsInsights(naaS, aaS, epRows, bestAht, bestFcr, bestShare) {
  const fcrGap = bestFcr.fcr - naaS.fcr;
  const ahtGap = naaS.aht - aaS.aht; // positive = AA faster
  const csatGap = aaS.csat - naaS.csat; // positive = AA higher
  return [
    `${bestAht.name} delivers the fastest handle time across every endpoint at ${fmtAHT(bestAht.aht)}, and already carries ${fmtPct(bestShare)} of total AA-routed volume -- the workflow is both fast and already well-adopted.`,
    `${bestFcr.name} leads on First Contact Resolution at ${fmtPct(bestFcr.fcr)}, ${Math.abs(fcrGap).toFixed(1)}pp ${fcrGap >= 0 ? 'above' : 'below'} the Non-AA baseline of ${fmtPct(naaS.fcr)}.`,
    `Across all endpoints combined, AA ${ahtGap >= 0 ? 'beats' : 'trails'} the Non-AA baseline by ${Math.abs(ahtGap).toFixed(1)}s on AHT and ${csatGap >= 0 ? 'leads by' : 'trails by'} ${Math.abs(csatGap).toFixed(1)}pp on CSAT -- ${(ahtGap >= 0 && csatGap >= 0) ? 'consistent evidence the assist is helping regardless of which endpoint handles the contact.' : 'worth a closer look at this specific filter slice against the unfiltered baseline.'}`,
  ];
}

// ══════════════════════════════════════════════════════════════════════════
// TAB 7 -- Agent Utilization
// ══════════════════════════════════════════════════════════════════════════
function renderAgentUtilization() {
  const u = DATA.agent_utilization;
  // Agent Utilization already breaks agents down into real overall/
  // alpha_group/ab_test_500pairs series, so the Agent Group filter selects
  // *among* those literal series (below) rather than re-scaling by a
  // profile -- scaling on top of an already-real breakdown would double
  // count. Channel filter still applies since there's no channel split in
  // the source data.
  const overall = scaledArr(u.trends.overall, 'count', { channelOnly: true });
  const alpha = scaledArr(u.trends.alpha_group, 'count', { channelOnly: true });
  const abTest = scaledArr(u.trends.ab_test_500pairs, 'count', { channelOnly: true });
  const cards = {
    overall: overall.at(-1), alpha_group: alpha.at(-1), ab_test_500pairs: abTest.at(-1),
  };
  const growthPct = ((overall.at(-1) - overall[0]) / overall[0]) * 100;
  const alphaShare = (cards.alpha_group / cards.overall) * 100;
  const abShare = (cards.ab_test_500pairs / cards.overall) * 100;

  document.getElementById('panel-agent-util').innerHTML = `
    <div class="kpi-grid">
      <div class="kpi-card"><div class="kpi-label">Overall Distinct Agents</div><div class="kpi-value">${fmtNum(cards.overall)}</div><div class="kpi-sub">Latest week</div></div>
      <div class="kpi-card"><div class="kpi-label">Baseline / Pilot Group</div><div class="kpi-value">${fmtNum(cards.alpha_group)}</div><div class="kpi-sub">Latest week</div></div>
      <div class="kpi-card"><div class="kpi-label">A/B Test (500 pairs)</div><div class="kpi-value">${fmtNum(cards.ab_test_500pairs)}</div><div class="kpi-sub">Latest week</div></div>
    </div>
    ${insightsCard('Strategic Insights -- Agent Utilization', agentUtilInsights(overall, growthPct, alphaShare, abShare, u.dates.length), metricReadout([
      { label: `Week 1 vs Week ${u.dates.length}`, aa: overall.at(-1), naa: overall[0], fmt: fmtNum },
    ]))}
    <div class="card"><h3>Distinct Active Agents -- Weekly Trend</h3><div class="chart-box"><canvas id="agentUtilTrend"></canvas></div></div>
  `;

  const groupKey = state.group === 'all' ? null : state.group;
  const datasets = [];
  if (!groupKey || groupKey === 'overall') datasets.push(lineDataset('Overall', overall, COLOR.overall));
  if (!groupKey || groupKey === 'alpha_group') datasets.push(lineDataset('Baseline / Pilot', alpha, COLOR.aa));
  if (!groupKey || groupKey === 'ab_test_500pairs') datasets.push(lineDataset('A/B Test (500 pairs)', abTest, '#10b981'));

  mkChart('agentUtilTrend', { type: 'line', data: { labels: u.date_labels, datasets }, options: baseLineOpts });
}

function agentUtilInsights(overall, growthPct, alphaShare, abShare, weeks) {
  return [
    `Distinct active agents grew ${growthPct.toFixed(1)}% over the trailing ${weeks} weeks (${fmtNum(overall[0])} \u2192 ${fmtNum(overall.at(-1))}), reflecting steady onboarding momentum rather than a one-time spike.`,
    `The Baseline / Pilot group represents ${alphaShare.toFixed(1)}% of overall utilization, with the A/B Test cohort at ${abShare.toFixed(1)}% -- the A/B slice is intentionally small to keep the comparison statistically clean while the broader rollout continues.`,
    `Sustained week-over-week growth in active agents is a leading indicator for the contact-volume and AHT gains seen elsewhere in this report -- more trained agents using AA compounds the program's impact over time.`,
  ];
}

// ══════════════════════════════════════════════════════════════════════════
// Tab switching + filter wiring + init
// ══════════════════════════════════════════════════════════════════════════
const RENDERERS = {
  'metric-defs': renderMetricDefs,
  'core-metrics-kpis': renderExecutiveSummary,
  'exec-summary': renderAht,
  'sentiment-score': renderSentiment,
  'aht-workflow': renderWorkflow,
  'core-metrics': renderCoreMetricsByEndpoint,
  'agent-util': renderAgentUtilization,
};

let activeTab = 'metric-defs';

function showTab(tabId) {
  activeTab = tabId;
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === tabId));
  document.querySelectorAll('.tab-panel').forEach(p => p.classList.toggle('active', p.id === `panel-${tabId}`));
  RENDERERS[tabId]();
}

document.getElementById('tabs').addEventListener('click', e => {
  const btn = e.target.closest('.tab-btn');
  if (btn) showTab(btn.dataset.tab);
});

['filterChannel', 'filterGroup', 'filterGrain'].forEach(id => {
  document.getElementById(id).addEventListener('change', e => {
    if (id === 'filterChannel') state.channel = e.target.value;
    if (id === 'filterGroup') state.group = e.target.value;
    if (id === 'filterGrain') state.grain = e.target.value;
    RENDERERS[activeTab]();
  });
});

showTab('metric-defs');
